# Generated by Django 4.1.7 on 2023-04-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facsch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btfacultyinfo',
            name='WorkHours',
        ),
    ]
