# Generated by Django 4.1.7 on 2023-04-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facsch', '0002_remove_btfacultyinfo_workhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='btfacultyinfo',
            name='WorkingHours',
            field=models.IntegerField(default=0),
        ),
    ]
