# Generated by Django 4.1.7 on 2023-03-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTRollLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cycle', models.IntegerField(choices=[('10', 'PHYSICS'), ('9', 'CHEMISTRY')], default=0)),
                ('Section', models.CharField(default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='BTStudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=255)),
                ('Regulation', models.FloatField()),
                ('Dept', models.IntegerField()),
                ('AdmissionYear', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Category', models.CharField(max_length=30)),
                ('GuardinaName', models.CharField(max_length=255)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address1', models.TextField()),
                ('Address2', models.TextField(null=True)),
                ('Cycle', models.IntegerField(choices=[('10', 'PHYSICS'), ('9', 'CHEMISTRY')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BTSubjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Sem', models.IntegerField()),
                ('Regulation', models.FloatField()),
                ('Mode', models.CharField(max_length=1)),
                ('Dept', models.IntegerField()),
                ('SubId', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=100)),
                ('Credits', models.IntegerField()),
                ('Type', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BTStudnetRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mode', models.IntegerField()),
                ('Student', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='seating.btrolllists')),
                ('Sub_Id', models.ForeignKey(db_column='sub_id', on_delete=django.db.models.deletion.CASCADE, to='seating.btsubjectinfo')),
            ],
        ),
        migrations.AddField(
            model_name='btrolllists',
            name='Student',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='seating.btstudentinfo'),
        ),
    ]
