# Generated by Django 4.1.7 on 2023-03-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='btstudentinfo',
            constraint=models.UniqueConstraint(fields=('RegNo',), name='unique_BTStudnetInfo_RegNo'),
        ),
        migrations.AddConstraint(
            model_name='btstudentinfo',
            constraint=models.UniqueConstraint(fields=('RollNo',), name='unique_BTStudentInfo_RollNo'),
        ),
    ]
