# Generated by Django 4.1.7 on 2023-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0002_btstudentinfo_unique_btstudnetinfo_regno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btstudentinfo',
            name='Phone',
            field=models.CharField(max_length=20),
        ),
    ]
