# Generated by Django 4.1.7 on 2023-04-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0004_alter_btstudentinfo_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btrolllists',
            name='Cycle',
            field=models.IntegerField(choices=[(10, 'PHYSICS'), (9, 'CHEMISTRY')], default=0),
        ),
    ]
